# Generated by Django 5.0.6 on 2024-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('buyer', 'Comprador')], default='buyer', max_length=10),
        ),
    ]
